name: TOC Generation Workflow Completed

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  validate-commit-message:
    runs-on: ubuntu-22.04
    outputs:
      passed: ${{ steps.validate-message.outputs.passed }}
    steps:
      - name: Verify commit message contains...
        id: validate-message
        run: |
          commit_message="${{ github.event.head_commit.message }}"

          if [[ "$commit_message" == *"Update package.json"* ]]; then
            echo "::notice::Commit message matches"
            echo "passed=1" >> $GITHUB_OUTPUT
          else
            echo "::notice::Commit message does not match"
          fi

  toc-generator:
    needs: [validate-commit-message]
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-toc-generator.yaml@main
    if: ${{ needs.validate-commit-message.outputs.passed == '1' }}
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      target-paths: 'README*.md,Docs/README*.md'
      check-only-default-branch: true