name: Release from default branch manually

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag you want to create (e.g., 1.0.0).'
        required: true
        type: string
      clean-branch:
        description: 'Delete the branch? All branches except the default branch will be deleted.'
        default: false
        type: boolean
      dry-run:
        description: 'Dry Run: Set to true to simulate the merge without committing or pushing changes.'
        default: false
        type: boolean
      fast-forward:
        description: 'Allow fast-forward merge'
        type: boolean
        required: false
        default: false

env:
  PACKAGEJSON_PATH: './Packages/SimplePackage/package.json'

jobs:
  update-packagejson:
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-update-packagejson.yaml@main
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      ref: ${{ github.event.repository.default_branch }}
      file-path: ${{ env.PACKAGEJSON_PATH }}
      tag: ${{ inputs.tag }}
      dry-run: ${{ inputs.dry-run }}

  release-notes:
    needs: [update-packagejson]
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-release-notes.yaml@main
    with:
      commit-id: ${{ needs.update-packagejson.outputs.sha }}

  create-release:
    needs: [update-packagejson, release-notes]
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-create-release.yaml@main
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      commit-id: ${{ needs.update-packagejson.outputs.sha }}
      dry-run: ${{ inputs.dry-run }}
      tag: ${{ inputs.tag }}
      release-note: ${{ needs.release-notes.outputs.notes }}