name: C# Linter with StyleCop (Simple Script Linter)

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: C# Linter Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Detect changed C# files
        id: detect_cs_files
        run: |
          cs_files=$(git diff --name-only origin/main...HEAD | grep '\.cs$' || true)

          if [ -z "$cs_files" ]; then
            echo "No C# files were changed in this PR."
            exit 0
          fi

          echo "Changed C# Files:"
          echo "$cs_files"

          echo "::set-output name=cs_files::$cs_files"

      - name: Setup .NET
        if: steps.detect_cs_files.outputs.cs_files != ''
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Run StyleCop
        if: steps.detect_cs_files.outputs.cs_files != ''
        run: |
          echo "Running StyleCop on the following files:"
          echo "${{ steps.detect_cs_files.outputs.cs_files }}"
          echo "${{ steps.detect_cs_files.outputs.cs_files }}" | xargs dotnet format --include

      - name: Apply Suggestions using reviewdog/action-suggester
        if: steps.detect_cs_files.outputs.cs_files != ''
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: StyleCop
          suggest_command: |
            echo "${{ steps.detect_cs_files.outputs.cs_files }}" | xargs git diff