name: Unity-Linter

on:
  pull_request:
    branches:
      - main

jobs:
  unity-lint:
    name: Run Unity-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Unity-Linter
        run: |
          npm install -g unity-linter

      - name: Run Unity-Linter
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep '\.cs$' || true)

          if [ -z "$files" ]; then
            echo "No C# files were changed in this PR."
            exit 0
          fi

          unity-linter --files $files || echo "Lint issues detected in Unity files."