name: C# Linter with StyleCop and reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run dotnet-format and report with reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Run dotnet-format
        run: |
          dotnet format
          git diff > patch.diff || true

      - name: Apply Suggestions using reviewdog/action-suggester
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: dotnet-format
          suggest_file: patch.diff
