name: Unity-CSharp-Linter

on:
  pull_request:
    branches:
      - main

jobs:
  unity-csharp-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install .NET and Roslyn analyzers
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-format

      - name: Detect Changed C# Files
        id: detect_cs_files
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep '\.cs$' || true)

          if [ -z "$files" ]; then
            echo "No C# files were changed in this PR."
            exit 0
          fi

          length=$(echo "$files" | wc -l)
          echo "::notice title=Detected changed C# files.::$length files"

          echo "::group::Detected changed C# files."
            echo "$files"
          echo "::endgroup::"
          echo "files=$files" >> "$GITHUB_OUTPUT"

      - name: Analyze and Format C# Code
        if: steps.detect_cs_files.outputs.cs_files != ''
        run: |
          cs_files=${{ steps.detect_cs_files.outputs.cs_files }}
          echo "Analyzing changed files..."
          for file in $cs_files; do
            echo "Analyzing $file"
            dotnet format $file || echo "Formatting issues detected in $file"
          done