name: Unity-CSharp-Linter

on:
  pull_request:
    branches:
      - main

jobs:
  unity-csharp-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install .NET and Roslyn analyzers
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-format

      - name: Detect Changed C# Files
        id: detect_cs_files
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep '\.cs$' || true)

          if [ -z "$files" ]; then
            echo "No C# files were changed in this PR."
            exit 0
          fi

          length=$(echo "$files" | wc -l)
          echo "::notice title=Detected changed C# files.::$length files"

          echo "::group::Detected changed C# files."
            echo "$files"
          echo "::endgroup::"
          echo "files=$files" >> "$GITHUB_OUTPUT"

      - name: Analyze C# Code using Roslyn Analyzers
        run: |
          echo "Creating temporary project for analysis"

          echo "<Project Sdk=\"Microsoft.NET.Sdk\">" > TempProject.csproj
          echo "  <ItemGroup>" >> TempProject.csproj
          for file in ${{ steps.detect_cs_files.outputs.files }}; do
            echo "    <Compile Include=\"$file\" />" >> TempProject.csproj
          done
          echo "  </ItemGroup>" >> TempProject.csproj

          dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers --version 3.3.2

          echo "Running Roslyn Analyzers..."
          dotnet build --no-restore TempProject.csproj || {
            echo "::error ::Static analysis failed."
            exit 1 
          }
