name: Unity-CSharp-Linter

on:
  pull_request:
    branches:
      - main

jobs:
  unity-csharp-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET and Roslyn analyzers
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-format

      - name: Detect Changed C# Files
        id: detect_cs_files
        run: |
          files=$(git diff --name-only origin/main...HEAD | grep '\.cs$' || true)

          if [ -z "$files" ]; then
            echo "No C# files were changed in this PR."
            exit 0
          fi

          echo "Detected changed C# files."
          echo "$files"
          echo "files=$files" >> $GITHUB_ENV

      - name: Analyze and Format C# Code
        run: |
          echo "Analyzing changed files..."
          for file in ${{ env.files }}; do
            echo "Analyzing $file"
            dotnet format $file || echo "Formatting issues detected in $file"
          done