name: Reviewdog actionlint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/actions/**'
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          fail_level: error