name: Lint Unity Csharp

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Assets/**'

permissions:
  pull-requests: write

jobs:
  release-notes:
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-unity-cs-linter-pull-request.yaml@main
    with:
      head-branch: ${{ github.event.pull_request.head.ref }}
      base-branch: ${{ github.event.pull_request.base.ref }}
      editorconfig-branch: ${{ github.event.repository.default_branch }}
      include-paths: 'Assets/Tests/StyleTest/.*'
      exclude-paths: 'Assets/Tests/StyleTest/FileNameIssueStyleViolationTest.cs'