name: Lint Unity Csharp

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Assets/**'

jobs:
  release-notes:
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-unity-cs-linter.yaml@main
    with:
      head-branch: ${{ github.event.pull_request.head.ref }}
      base-branch: ${{ github.event.pull_request.base.ref }}
      include-paths: 'Assets/Tests/StyleTest/.*'