name: Lint Unity Csharp for Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Assets/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  release-notes:
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-unity-cs-linter-pull-request.yaml@main
    with:
      head-branch: ${{ github.event.pull_request.head.ref }}
      base-branch: ${{ github.event.pull_request.base.ref }}
      editorconfig-branch: ${{ github.event.repository.default_branch }}
      # regex https://www.gnu.org/software/grep/manual/
      include-paths: 'Assets/Scripts/.*'
      exclude-paths: 'Assets/Scripts/.*Violations\.cs$'