name: (Reusable) Test Runner

on:
  workflow_call:
    inputs:
      unity-version:
        description: 'Version of Unity to use for testing the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt. ⚠️ If testing a Unity Package, this field is required and cannot be set to "auto". https://game.ci/docs/docker/versions/'
        required: false
        type: string
        default: 'auto'
      project-path:
        description: 'Specify the path to your Unity project or package to be tested. The path should be relative to the root of your project.'
        required: false
        type: string
        default: ''
      test-modes:
        description: 'Comma-separated test modes (e.g., playmode,editmode,standalone).'
        required: false
        type: string
        default: 'playmode,editmode'
      custom-parameters:
        description: 'Custom parameters to configure the test runner.  https://game.ci/docs/github/test-runner/#customparameters'
        required: false
        type: string
        default: ''
    secrets:
      UNITY_LICENSE:
        required: true
      UNITY_EMAIL:
        required: true
      UNITY_PASSWORD:
        required: true

jobs:
  prepare-test-modes:
    runs-on: ubuntu-latest
    outputs:
      array: ${{ steps.set-array.outputs.array }}
    steps:
      - name: Convert test modes to array
        id: set-array
        run: |
          if [[ "${{ inputs.test-modes }}" == *","* ]]; then
            echo '::set-output name=array::["'$(echo "${{ inputs.test-modes }}" | sed 's/,/","/g')'"]'
          else
            echo '::set-output name=array::["${{ inputs.test-modes }}"]'
          fi

  test-all:
    needs: [prepare-test-modes]
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        unity-version: ${{ inputs.unity-version }}
        projectPath: ${{ inputs.project-path }}
        testMode: ${{ fromJson(needs.prepare-test-modes.outputs.array) }}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v4
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}