name: (Reusable) Unity C# Linter

on:
  workflow_call:
    inputs:
      head-branch:
        description: 'Target head branch for investigation'
        required: true
        type: string
      base-branch:
        description: 'Target base branch for investigation'
        required: false
        type: string
        default: ''
      editorconfig-branch:
        description: 'Branch where .editorconfig is placed. If not specified, base-branch will be used.'
        required: false
        type: string
        default: ''
      include_paths:
        description: 'Include files or directories (regex, comma-separated). For more information https://www.gnu.org/software/grep/manual/'
        required: false
        type: string
        default: 'Assets/.*'
      exclude_paths:
        description: 'Exclude files or directories (regex, comma-separated)'
        required: false
        type: string
        default: ''

env:
  EDITORCONFIG_SAMPLE_URI: 'https://github.com/IShix-g/Unity-GitHubActions/blob/main/.editorconfig'
  CONVERT_TO_SARIF_URI: 'https://raw.githubusercontent.com/IShix-g/Unity-GitHubActions/HEAD/.github/scripts/convert_to_sarif.py'

jobs:
  branch-conf:
    runs-on: ubuntu-22.04
    outputs:
      base-branch: ${{ steps.branch-conf.outputs.base-branch }}
      head-branch: ${{ steps.branch-conf.outputs.head-branch }}
      editorconfig-branch: ${{ steps.branch-conf.outputs.editorconfig-branch }}
    steps:
      - name: Set Base Branch
        id: branch-conf
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "${{ inputs.base-branch }}" ]; then
            base_branch="${{ inputs.base-branch }}"
          else
            base_branch=$(gh api /repos/${{ github.repository }} --jq '.base_branch')
          fi
          echo "base-branch=${base_branch#refs/heads/}" >> "$GITHUB_OUTPUT"

          if [ -n "${{ inputs.head-branch }}" ]; then
            head_branch="${{ inputs.head-branch }}"
            echo "head-branch=${head_branch#refs/heads/}" >> "$GITHUB_OUTPUT"
          fi

          if [ -n "${{ inputs.editorconfig-branch }}" ]; then
            editorconfig_branch="${{ inputs.editorconfig-branch }}"
          else
            editorconfig_branch=$base_branch
          fi
          echo "editorconfig-branch=${editorconfig_branch#refs/heads/}" >> "$GITHUB_OUTPUT"

          echo "::notice title=Base Branch::$base_branch"
          echo "::notice title=Head Branch::$head_branch"
          echo "::notice title=Editorconfig Branch::$editorconfig_branch"

  check-editorconfig:
    needs: [branch-conf]
    runs-on: ubuntu-22.04
    steps:
      - name: Check for .editorconfig via API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch=${{ needs.branch-conf.outputs.editorconfig-branch }}
          file_path=".editorconfig"
          max_retries=3
          retry_delay=5  # sec
  
          for ((i=1; i<=max_retries; i++)); do
            response=$(timeout 10s gh api repos/${{ github.repository }}/contents/$file_path --jq '. | select(.type=="file") | select(.name=="'$file_path'")')

            if [ $? -eq 124 ]; then
              echo "Attempt $i: Timeout occurred while requesting GitHub API. Retrying in $retry_delay seconds..."
              sleep $retry_delay
            elif [ -z "$response" ]; then
              if [ $i -eq $max_retries ]; then
                echo "::error title=.editorconfig Missing::The root of the repository is missing an .editorconfig file. For reference, you can look at: ${{ env.EDITORCONFIG_SAMPLE_URI }}"
              exit 1
            fi
            else
              echo ".editorconfig file exists at the root of the repository."
            fi
          done

  lint-cs-files:
    needs: [branch-conf, check-editorconfig]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.branch-conf.outputs.head-branch || needs.branch-conf.outputs.base-branch }}
          fetch-depth: 0

      - name: Detect Changed C# Files
        id: detect-cs-files
        run: |
          files=$(git diff --name-only origin/${{ needs.branch-conf.outputs.base-branch }}...${{ needs.branch-conf.outputs.head-branch || 'HEAD' }} | grep '\.cs$' || true)
          if [ -z "$files" ]; then
            echo "No C# files were changed in this PR."
            exit 0
          fi

          include_regexes=$(echo "${{ inputs.include_paths }}" | tr ',' '\n')
          exclude_regexes=$(echo "${{ inputs.exclude_paths }}" | tr ',' '\n')

          included_files=""
          for file in $files; do
            include_matched=false
            exclude_matched=false

            for regex in $include_regexes; do
              if [[ "$file" =~ $regex ]]; then
                include_matched=true
              fi
            done

            for regex in $exclude_regexes; do
              if [[ "$file" =~ $regex ]]; then
                exclude_matched=true
              fi
            done

            if $include_matched && ! $exclude_matched; then
              included_files+="${file}\n"
            fi
          done

          if [ -z "$included_files" ]; then
            echo "No C# files matched the include/exclude criteria."
            exit 0
          fi

          included_files=$(echo -e "$included_files" | sed '/^\s*$/d' | tr '\n' ',')
          included_files=$(echo "$included_files" | sed 's/,$//' )
          echo "files=$included_files" >> "$GITHUB_OUTPUT"

      - name: Create Temporary csproj for Analysis
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          echo "<Project Sdk=\"Microsoft.NET.Sdk\">" > TempProject.csproj
          echo "  <PropertyGroup>" >> TempProject.csproj
          echo "    <TargetFramework>netstandard2.1</TargetFramework>" >> TempProject.csproj
          echo "    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>" >> TempProject.csproj
          echo "  </PropertyGroup>" >> TempProject.csproj
          echo "  <ItemGroup>" >> TempProject.csproj
          IFS=',' read -ra files <<< "${{ steps.detect-cs-files.outputs.files }}"
          for file in "${files[@]}"; do
            echo "    <Compile Include=\"$file\" />" >> TempProject.csproj
          done
          echo "  </ItemGroup>" >> TempProject.csproj
          echo "</Project>" >> TempProject.csproj

      - name: Debug csproj
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          echo "=== TempProject.csproj ==="
          cat TempProject.csproj
          echo "=== end ==="

      - name: Install .NET SDK
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Install StyleCop and dotnet-format
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-format
          dotnet add package StyleCop.Analyzers

      - name: Collect Style Violations Log
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          echo "Collecting style violations into output.log..."
          dotnet format TempProject.csproj --verify-no-changes >> output.log 2>&1 \
          || echo "Style violation detected" >> output.log
          
          while IFS= read -r line; do
              modified_line=$(echo "$line" | sed -E 's/(\\s){6}/6 spaces/g' | sed -E 's/(\\s){4}/4 spaces/g' | sed -E 's/(\\s){2}/2 spaces/g' | sed -E 's/\\s/1 space/g')
              echo "$modified_line" >> output_temp.log
          done < output.log
          mv output_temp.log output.log

      - name: Debug Raw Output Log
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          echo "=== DEBUG RAW OUTPUT.LOG ==="
          cat output.log
          echo "=== END RAW OUTPUT.LOG ==="

      - name: Download `convert_to_sarif.py`
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          curl --fail --silent --show-error --max-time 10 -o convert_to_sarif.py ${{ env.CONVERT_TO_SARIF_URI }} || { echo "Failed to download script"; exit 1; }

      - name: Convert to SARIF
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        run: |
          python3 convert_to_sarif.py output.log output.sarif

      - name: Setup reviewdog
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Apply Style Suggestions with reviewdog
        if: ${{ steps.detect-cs-files.outputs.files != '' }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -f=sarif \
            -name="StyleCop" \
            -reporter=github-pr-review \
            -filter-mode=file \
            -level=warning \
            -fail-level=error \
            < output.sarif

      - name: Cleanup temporary files
        if: ${{ steps.detect-cs-files.outputs.files != '' && always() }}
        run: |
          rm -f TempProject.csproj convert_to_sarif.py output.log output.sarif || true
