name: "(Reusable) Check .editorconfig"

on:
  workflow_call:
    inputs:
      ref:
        description: "Specify a branch or commit ID"
        required: true
        type: string
      max-retries:
        description: "Maximum number of retries if API call fails"
        required: false
        type: string
        default: "3"
      retry-delay:
        description: "Delay in seconds between retries"
        required: false
        type: string
        default: "5"
      fail-on-missing:
        description: "Fail the workflow if .editorconfig does not exist"
        required: false
        type: boolean
        default: true
    outputs:
      exists:
        description: "Indicates whether the .editorconfig file exists"
        value: ${{ jobs.check-editorconfig.outputs.exists }}

jobs:
  check-editorconfig:
    runs-on: ubuntu-22.04
    outputs:
      exists: ${{ steps.check-editorconfig.outputs.exists }}
    steps:
      - name: Check out ${{ inputs.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1

      - name: Check for .editorconfig
        id: check-editorconfig
        run: |
          file_path=".editorconfig"
          fail_on_missing="${{ inputs.fail-on-missing }}"

          echo "Checking for file: $file_path in the checked-out repository..."

          success=false
          if [ -f "$file_path" ]; then
            echo "::notice::.editorconfig file exists."
            success=true
          else
            echo "::warning::.editorconfig file does not exist."
            if [ "$fail_on_missing" = "true" ]; then
              exit 1
            fi
          fi

          echo "exists=$success" | tee -a "$GITHUB_OUTPUT"
