name: (Test) Update package.json

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag you want to create (e.g., 1.0.0).'
        type: string
        default: ''
      require-validation:
        description: 'true requires validation to pass; false allows continuing even if validation fails.'
        type: boolean
        default: true
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: ''
      require-validation:
        required: false
        type: boolean
        default: true
    secrets:
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true

jobs:
  set-tag:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Set tag
        id: set-tag
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            tag="${{ inputs.tag }}"
          else
            tag="11.11.${{ github.run_number }}"
          fi
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "::notice::tag:$tag"

  update-packagejson:
    needs: [set-tag]
    uses: ./.github/workflows/reusable-update-packagejson.yaml
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      ref: ${{ github.ref }}
      file-path: ./Packages/TestSimplePackage/package.json
      tag: ${{ needs.set-tag.outputs.tag }}
      dry-run: true
      require-validation: ${{ inputs.require-validation }}

  test:
    needs: [set-tag, update-packagejson]
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Check update-packagejson with new version should update commit id
        run: |
          echo "DEBUG: Tag                   : ${{ needs.set-tag.outputs.tag }}"
          echo "DEBUG: GitHub SHA            : ${{ github.sha }}"
          echo "DEBUG: Update-packagejson SHA: ${{ needs.update-packagejson.outputs.sha }}"
          
          # Check conditions for dry-run
          echo -n "FACT: Dry-run is enabled. SHA should remain unchanged. "
          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "" ]]; then
            echo "[O PASS]"
          else
            echo "[X FAIL]" && exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fail test if dry-run commits any changes
        run: |
          echo "Verifying that no changes were committed during dry-run..."
          git fetch
          LOCAL_SHA=$(git rev-parse HEAD)
          echo "LOCAL_SHA: $LOCAL_SHA"
          if [[ "${{ needs.update-packagejson.outputs.sha }}" == "$LOCAL_SHA" ]]; then
            echo "[X FAIL] Dry-run unexpectedly resulted in a commit"
            exit 1
          fi
          echo "[O PASS] Dry-run correctly skipped the commit"

  cleanup:
    if: ${{ !inputs.dry-run && needs.update-packagejson.outputs.changed == '1' }}
    needs: [ update-packagejson ]
    uses: ./.github/workflows/reusable-clean-branch.yaml
    with:
      branch:  ${{ github.ref }}