name: (Test) Release Notes Generator

on:
  workflow_dispatch:
    inputs:
      from-tag:
        description: 'Start tag (default: first commit if unset)'
        type: string
        default: ''
      to-tag:
        description: 'End tag (default: latest commit if unset)'
        type: string
        default: ''
      commit-message-format:
        description: 'Commit message format (see https://git-scm.com/docs/pretty-formats)'
        type: string
        default: '- %s by %cn (%h)'
      derive-from-tag:
        description: 'true = Auto-determine from-tag using previous tags; false = Set manually.'
        type: boolean
        default: true

jobs:
  release-notes:
    uses: ./.github/workflows/reusable-release-notes.yaml
    with:
      from-tag: ${{ inputs.from-tag }}
      to-tag: ${{ inputs.to-tag }}
      commit-message-format: ${{ inputs.commit-message-format }}
      commit-id: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
      derive-from-tag: ${{ inputs.derive-from-tag }}