name: (Test) Unity C# Linter

on:
  pull_request:
    branches:
      - feature/csharp-lint

jobs:
  release-notes:
    uses: ./.github/workflows/reusable-unity-cs-linter.yaml
    with:
      branch: ${{ github.event.pull_request.head.ref }}