name: (Test) Unity C# Linter for Pull Request

on:
  pull_request:
    branches:
      - develop/unity-lint**

jobs:
  unity-cs-linter:
    uses: ./.github/workflows/reusable-unity-cs-linter-pull-request.yaml
    with:
      head-branch: ${{ github.event.pull_request.head.ref }}
      base-branch: ${{ github.event.pull_request.base.ref }}
      editorconfig-branch: ${{ github.event.pull_request.head.ref }}
      include-paths: 'Assets/Tests/StyleTest/.*'
      exclude-paths: 'Assets/Tests/StyleTest/FileNameIssueStyleViolationTest.cs'