name: TOC Generation via Push and PR

on:
  workflow_dispatch:
  push:
    tags-ignore:
      - '**'
  pull_request:

permissions:
  contents: write

jobs:
  validate-branch:
    runs-on: ubuntu-22.04
    outputs:
      passed: ${{ steps.check-branch.outputs.passed }}
    steps:
      - name: Check if ref is not default branch
        id: check-branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            target_branch="${{ github.event.pull_request.base.ref }}"
          else
            target_branch=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          fi

          default_branch="${{ github.event.repository.default_branch }}"

          if [[ "$target_branch" == "$default_branch" ]]; then
            echo "::notice::Branch check passed."
            echo "passed=1" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::This is not the default branch. ($default_branch)"
            echo "Target branch: $target_branch"
            echo "Default branch: $default_branch"
          fi

  validate-commit-message:
    runs-on: ubuntu-22.04
    outputs:
      passed: ${{ steps.validate-message.outputs.passed }}
    steps:
      - name: Verify commit message contains...
        id: validate-message
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          
          if [[ "$commit_message" != *"Update package.json"* ]]; then
            echo "::notice::Commit message does not match"
            echo "passed=1" >> $GITHUB_OUTPUT
          else
            echo "::notice::Commit message matches"
          fi

  toc-generator:
    needs: [validate-branch, validate-commit-message]
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-toc-generator.yaml@main
    if: ${{ needs.validate-branch.outputs.passed == '1' && needs.validate-commit-message.outputs.passed == '1' }}
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      target-paths: 'README*.md,Docs/README*.md'