name: TOC Generator via push

on: push

permissions:
  contents: write

jobs:
  toc-generator:
    uses: IShix-g/Unity-GitHubActions/.github/workflows/reusable-toc-generator.yaml@main
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
    with:
      target-paths: 'README*.md,Docs/README*.md'